---
roles:
  # Install a role from Ansible Galaxy.
  - name: os_prepare
    src: https://github.com/dnlouko/ansible-role-os-prepare.git
collections:
  - name: community.general
    source: https://galaxy.ansible.com
