---
- name: Install my Apps
  ansible.builtin.apt:
    name:
      - tree
      - okular
      - git
      - python3
      - python3-pip
      - python3-virtualenv
      - vim
      - docker
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - gimp
      - xz-utils
      - snapd
      - build-essential
      - procps
      - file
      - jq
      - git
      - curl
      - gnome-tweaks
      - gnome-sushi
      - gnome-weather
      - brave-browser
      - thunderbird
      - dnsmasq
      - balena-etcher-electron
      # - azure-cli
      # - spotify-client
      # - ttf-mscorefonts-installer
    state: present
    update_cache: true
  when: ansible_distribution == 'Pop!_OS'
